# Generated by Django 5.1.5 on 2025-02-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_adminregistershipforsale_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminregistershipforsale',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='ships', to='web.amenities'),
        ),
    ]
