# Generated by Django 5.1.5 on 2025-02-21 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_adminregistershipforsale_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='value',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.RemoveField(
            model_name='adminregistershipforsale',
            name='amenities',
        ),
        migrations.AddField(
            model_name='adminregistershipforsale',
            name='amenities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.amenities'),
        ),
    ]
