# Generated by Django 5.1.5 on 2025-02-21 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_amenities_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminregistershipforsale',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='value',
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='web.adminregistershipforsale')),
            ],
        ),
    ]
